test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -32,10 +32,10 @@ jobs:
         id: client
         run: |
           curl -o versions.json https://exp.host/--/api/v2/versions
-          sdk = $(cat versions.json | jq '.sdkVersions["${{github.event.inputs.sdkVersion}}"]')
-          if [[ -z sdk ]]; then echo 'Version ${{github.event.inputs.sdkVersion}} not found'; exit 1; fi
-          echo "::set-output name=version::$(echo $sdk | jq '.androidClientVersion')"
-          echo "::set-output name=url::$(echo $sdk | jq '.androidClientUrl')"
+          SDK = $(cat versions.json | jq '.sdkVersions["${{github.event.inputs.sdkVersion}}"]')
+          if [[ -z $SDK ]]; then echo 'Version ${{github.event.inputs.sdkVersion}} not found'; exit 1; fi
+          echo "::set-output name=version::$(echo $SDK | jq '.androidClientVersion')"
+          echo "::set-output name=url::$(echo $SDK | jq '.androidClientUrl')"
 
       # - name: Validate Android client
       #   uses: actions/github-script@v4
